# official Ruby image as the base image
FROM ruby:latest

# working directory inside the container
WORKDIR /mnt/c/Users/scoob/OneDrive/Documents/MesaCollege/ComputerScience/ProgrammingLaunguage/language-ssmedina2/Object_Oriented_Paradigm/SubtrationCode

# Copy Ruby files into the container
COPY . /mnt/c/Users/scoob/OneDrive/Documents/MesaCollege/ComputerScience/ProgrammingLaunguage/language-ssmedina2/Object_Oriented_Paradigm/SubtrationCode

# Run the Ruby code
CMD ["ruby", "main.rb"]
