# official Python runtime as base image 
FROM python:3.8-slim

# working directory inside the container
WORKDIR /mnt/c/Users/scoob/OneDrive/Documents/MesaCollege/ComputerScience/ProgrammingLaunguage/language-ssmedina2/Parse_Strings

# Copy Python files into the container
COPY . /mnt/c/Users/scoob/OneDrive/Documents/MesaCollege/ComputerScience/ProgrammingLaunguage/language-ssmedina2/Parse_Strings

# Run the program
CMD ["python", "./Main.py"]